package com.shiyu.demo.entity;

import java.util.Date;

public class CommunityPost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_post.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_post.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_post.posttext
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String posttext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_post.posttop
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer posttop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_post.postdown
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer postdown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_post.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_post.postname
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String postname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_post.createdate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_post.aboutid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer aboutid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_post.id
     *
     * @return the value of community_post.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_post.id
     *
     * @param id the value for community_post.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_post.userid
     *
     * @return the value of community_post.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_post.userid
     *
     * @param userid the value for community_post.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_post.posttext
     *
     * @return the value of community_post.posttext
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getPosttext() {
        return posttext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_post.posttext
     *
     * @param posttext the value for community_post.posttext
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setPosttext(String posttext) {
        this.posttext = posttext == null ? null : posttext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_post.posttop
     *
     * @return the value of community_post.posttop
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getPosttop() {
        return posttop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_post.posttop
     *
     * @param posttop the value for community_post.posttop
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setPosttop(Integer posttop) {
        this.posttop = posttop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_post.postdown
     *
     * @return the value of community_post.postdown
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getPostdown() {
        return postdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_post.postdown
     *
     * @param postdown the value for community_post.postdown
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setPostdown(Integer postdown) {
        this.postdown = postdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_post.shopid
     *
     * @return the value of community_post.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_post.shopid
     *
     * @param shopid the value for community_post.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_post.postname
     *
     * @return the value of community_post.postname
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getPostname() {
        return postname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_post.postname
     *
     * @param postname the value for community_post.postname
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setPostname(String postname) {
        this.postname = postname == null ? null : postname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_post.createdate
     *
     * @return the value of community_post.createdate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_post.createdate
     *
     * @param createdate the value for community_post.createdate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_post.aboutid
     *
     * @return the value of community_post.aboutid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getAboutid() {
        return aboutid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_post.aboutid
     *
     * @param aboutid the value for community_post.aboutid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setAboutid(Integer aboutid) {
        this.aboutid = aboutid;
    }
}