package com.shiyu.demo.entity;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.usercoid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer usercoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commenttext
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String commenttext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String commentimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.type
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.usercoid
     *
     * @return the value of comment.usercoid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getUsercoid() {
        return usercoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.usercoid
     *
     * @param usercoid the value for comment.usercoid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUsercoid(Integer usercoid) {
        this.usercoid = usercoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userid
     *
     * @return the value of comment.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userid
     *
     * @param userid the value for comment.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commenttext
     *
     * @return the value of comment.commenttext
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getCommenttext() {
        return commenttext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commenttext
     *
     * @param commenttext the value for comment.commenttext
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCommenttext(String commenttext) {
        this.commenttext = commenttext == null ? null : commenttext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentimg
     *
     * @return the value of comment.commentimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getCommentimg() {
        return commentimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentimg
     *
     * @param commentimg the value for comment.commentimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCommentimg(String commentimg) {
        this.commentimg = commentimg == null ? null : commentimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.type
     *
     * @return the value of comment.type
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.type
     *
     * @param type the value for comment.type
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }
}