package com.shiyu.demo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommunityPostExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public CommunityPostExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andPosttextIsNull() {
            addCriterion("posttext is null");
            return (Criteria) this;
        }

        public Criteria andPosttextIsNotNull() {
            addCriterion("posttext is not null");
            return (Criteria) this;
        }

        public Criteria andPosttextEqualTo(String value) {
            addCriterion("posttext =", value, "posttext");
            return (Criteria) this;
        }

        public Criteria andPosttextNotEqualTo(String value) {
            addCriterion("posttext <>", value, "posttext");
            return (Criteria) this;
        }

        public Criteria andPosttextGreaterThan(String value) {
            addCriterion("posttext >", value, "posttext");
            return (Criteria) this;
        }

        public Criteria andPosttextGreaterThanOrEqualTo(String value) {
            addCriterion("posttext >=", value, "posttext");
            return (Criteria) this;
        }

        public Criteria andPosttextLessThan(String value) {
            addCriterion("posttext <", value, "posttext");
            return (Criteria) this;
        }

        public Criteria andPosttextLessThanOrEqualTo(String value) {
            addCriterion("posttext <=", value, "posttext");
            return (Criteria) this;
        }

        public Criteria andPosttextLike(String value) {
            addCriterion("posttext like", value, "posttext");
            return (Criteria) this;
        }

        public Criteria andPosttextNotLike(String value) {
            addCriterion("posttext not like", value, "posttext");
            return (Criteria) this;
        }

        public Criteria andPosttextIn(List<String> values) {
            addCriterion("posttext in", values, "posttext");
            return (Criteria) this;
        }

        public Criteria andPosttextNotIn(List<String> values) {
            addCriterion("posttext not in", values, "posttext");
            return (Criteria) this;
        }

        public Criteria andPosttextBetween(String value1, String value2) {
            addCriterion("posttext between", value1, value2, "posttext");
            return (Criteria) this;
        }

        public Criteria andPosttextNotBetween(String value1, String value2) {
            addCriterion("posttext not between", value1, value2, "posttext");
            return (Criteria) this;
        }

        public Criteria andPosttopIsNull() {
            addCriterion("posttop is null");
            return (Criteria) this;
        }

        public Criteria andPosttopIsNotNull() {
            addCriterion("posttop is not null");
            return (Criteria) this;
        }

        public Criteria andPosttopEqualTo(Integer value) {
            addCriterion("posttop =", value, "posttop");
            return (Criteria) this;
        }

        public Criteria andPosttopNotEqualTo(Integer value) {
            addCriterion("posttop <>", value, "posttop");
            return (Criteria) this;
        }

        public Criteria andPosttopGreaterThan(Integer value) {
            addCriterion("posttop >", value, "posttop");
            return (Criteria) this;
        }

        public Criteria andPosttopGreaterThanOrEqualTo(Integer value) {
            addCriterion("posttop >=", value, "posttop");
            return (Criteria) this;
        }

        public Criteria andPosttopLessThan(Integer value) {
            addCriterion("posttop <", value, "posttop");
            return (Criteria) this;
        }

        public Criteria andPosttopLessThanOrEqualTo(Integer value) {
            addCriterion("posttop <=", value, "posttop");
            return (Criteria) this;
        }

        public Criteria andPosttopIn(List<Integer> values) {
            addCriterion("posttop in", values, "posttop");
            return (Criteria) this;
        }

        public Criteria andPosttopNotIn(List<Integer> values) {
            addCriterion("posttop not in", values, "posttop");
            return (Criteria) this;
        }

        public Criteria andPosttopBetween(Integer value1, Integer value2) {
            addCriterion("posttop between", value1, value2, "posttop");
            return (Criteria) this;
        }

        public Criteria andPosttopNotBetween(Integer value1, Integer value2) {
            addCriterion("posttop not between", value1, value2, "posttop");
            return (Criteria) this;
        }

        public Criteria andPostdownIsNull() {
            addCriterion("postdown is null");
            return (Criteria) this;
        }

        public Criteria andPostdownIsNotNull() {
            addCriterion("postdown is not null");
            return (Criteria) this;
        }

        public Criteria andPostdownEqualTo(Integer value) {
            addCriterion("postdown =", value, "postdown");
            return (Criteria) this;
        }

        public Criteria andPostdownNotEqualTo(Integer value) {
            addCriterion("postdown <>", value, "postdown");
            return (Criteria) this;
        }

        public Criteria andPostdownGreaterThan(Integer value) {
            addCriterion("postdown >", value, "postdown");
            return (Criteria) this;
        }

        public Criteria andPostdownGreaterThanOrEqualTo(Integer value) {
            addCriterion("postdown >=", value, "postdown");
            return (Criteria) this;
        }

        public Criteria andPostdownLessThan(Integer value) {
            addCriterion("postdown <", value, "postdown");
            return (Criteria) this;
        }

        public Criteria andPostdownLessThanOrEqualTo(Integer value) {
            addCriterion("postdown <=", value, "postdown");
            return (Criteria) this;
        }

        public Criteria andPostdownIn(List<Integer> values) {
            addCriterion("postdown in", values, "postdown");
            return (Criteria) this;
        }

        public Criteria andPostdownNotIn(List<Integer> values) {
            addCriterion("postdown not in", values, "postdown");
            return (Criteria) this;
        }

        public Criteria andPostdownBetween(Integer value1, Integer value2) {
            addCriterion("postdown between", value1, value2, "postdown");
            return (Criteria) this;
        }

        public Criteria andPostdownNotBetween(Integer value1, Integer value2) {
            addCriterion("postdown not between", value1, value2, "postdown");
            return (Criteria) this;
        }

        public Criteria andShopidIsNull() {
            addCriterion("shopid is null");
            return (Criteria) this;
        }

        public Criteria andShopidIsNotNull() {
            addCriterion("shopid is not null");
            return (Criteria) this;
        }

        public Criteria andShopidEqualTo(Integer value) {
            addCriterion("shopid =", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotEqualTo(Integer value) {
            addCriterion("shopid <>", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThan(Integer value) {
            addCriterion("shopid >", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopid >=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThan(Integer value) {
            addCriterion("shopid <", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThanOrEqualTo(Integer value) {
            addCriterion("shopid <=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidIn(List<Integer> values) {
            addCriterion("shopid in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotIn(List<Integer> values) {
            addCriterion("shopid not in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidBetween(Integer value1, Integer value2) {
            addCriterion("shopid between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotBetween(Integer value1, Integer value2) {
            addCriterion("shopid not between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andPostnameIsNull() {
            addCriterion("postname is null");
            return (Criteria) this;
        }

        public Criteria andPostnameIsNotNull() {
            addCriterion("postname is not null");
            return (Criteria) this;
        }

        public Criteria andPostnameEqualTo(String value) {
            addCriterion("postname =", value, "postname");
            return (Criteria) this;
        }

        public Criteria andPostnameNotEqualTo(String value) {
            addCriterion("postname <>", value, "postname");
            return (Criteria) this;
        }

        public Criteria andPostnameGreaterThan(String value) {
            addCriterion("postname >", value, "postname");
            return (Criteria) this;
        }

        public Criteria andPostnameGreaterThanOrEqualTo(String value) {
            addCriterion("postname >=", value, "postname");
            return (Criteria) this;
        }

        public Criteria andPostnameLessThan(String value) {
            addCriterion("postname <", value, "postname");
            return (Criteria) this;
        }

        public Criteria andPostnameLessThanOrEqualTo(String value) {
            addCriterion("postname <=", value, "postname");
            return (Criteria) this;
        }

        public Criteria andPostnameLike(String value) {
            addCriterion("postname like", value, "postname");
            return (Criteria) this;
        }

        public Criteria andPostnameNotLike(String value) {
            addCriterion("postname not like", value, "postname");
            return (Criteria) this;
        }

        public Criteria andPostnameIn(List<String> values) {
            addCriterion("postname in", values, "postname");
            return (Criteria) this;
        }

        public Criteria andPostnameNotIn(List<String> values) {
            addCriterion("postname not in", values, "postname");
            return (Criteria) this;
        }

        public Criteria andPostnameBetween(String value1, String value2) {
            addCriterion("postname between", value1, value2, "postname");
            return (Criteria) this;
        }

        public Criteria andPostnameNotBetween(String value1, String value2) {
            addCriterion("postname not between", value1, value2, "postname");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createdate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createdate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createdate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createdate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createdate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createdate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createdate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createdate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createdate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createdate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createdate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createdate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andAboutidIsNull() {
            addCriterion("aboutid is null");
            return (Criteria) this;
        }

        public Criteria andAboutidIsNotNull() {
            addCriterion("aboutid is not null");
            return (Criteria) this;
        }

        public Criteria andAboutidEqualTo(Integer value) {
            addCriterion("aboutid =", value, "aboutid");
            return (Criteria) this;
        }

        public Criteria andAboutidNotEqualTo(Integer value) {
            addCriterion("aboutid <>", value, "aboutid");
            return (Criteria) this;
        }

        public Criteria andAboutidGreaterThan(Integer value) {
            addCriterion("aboutid >", value, "aboutid");
            return (Criteria) this;
        }

        public Criteria andAboutidGreaterThanOrEqualTo(Integer value) {
            addCriterion("aboutid >=", value, "aboutid");
            return (Criteria) this;
        }

        public Criteria andAboutidLessThan(Integer value) {
            addCriterion("aboutid <", value, "aboutid");
            return (Criteria) this;
        }

        public Criteria andAboutidLessThanOrEqualTo(Integer value) {
            addCriterion("aboutid <=", value, "aboutid");
            return (Criteria) this;
        }

        public Criteria andAboutidIn(List<Integer> values) {
            addCriterion("aboutid in", values, "aboutid");
            return (Criteria) this;
        }

        public Criteria andAboutidNotIn(List<Integer> values) {
            addCriterion("aboutid not in", values, "aboutid");
            return (Criteria) this;
        }

        public Criteria andAboutidBetween(Integer value1, Integer value2) {
            addCriterion("aboutid between", value1, value2, "aboutid");
            return (Criteria) this;
        }

        public Criteria andAboutidNotBetween(Integer value1, Integer value2) {
            addCriterion("aboutid not between", value1, value2, "aboutid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table community_post
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 26 19:29:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}