package com.shiyu.demo.entity;

public class CommunityImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_img.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_img.img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_img.id
     *
     * @return the value of community_img.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_img.id
     *
     * @param id the value for community_img.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_img.img
     *
     * @return the value of community_img.img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_img.img
     *
     * @param img the value for community_img.img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}