package com.shiyu.demo.entity;

public class MenuImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_img.imgid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer imgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_img.menuid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_img.imgurl
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String imgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_img.imgid
     *
     * @return the value of menu_img.imgid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getImgid() {
        return imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_img.imgid
     *
     * @param imgid the value for menu_img.imgid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setImgid(Integer imgid) {
        this.imgid = imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_img.menuid
     *
     * @return the value of menu_img.menuid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_img.menuid
     *
     * @param menuid the value for menu_img.menuid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_img.imgurl
     *
     * @return the value of menu_img.imgurl
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_img.imgurl
     *
     * @param imgurl the value for menu_img.imgurl
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }
}