package com.shiyu.demo.entity;

public class PostImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_img.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_img.postid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer postid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_img.postimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String postimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_img.id
     *
     * @return the value of post_img.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_img.id
     *
     * @param id the value for post_img.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_img.postid
     *
     * @return the value of post_img.postid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_img.postid
     *
     * @param postid the value for post_img.postid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setPostid(Integer postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_img.postimg
     *
     * @return the value of post_img.postimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getPostimg() {
        return postimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_img.postimg
     *
     * @param postimg the value for post_img.postimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setPostimg(String postimg) {
        this.postimg = postimg == null ? null : postimg.trim();
    }
}