package com.shiyu.demo.entity;

import java.util.Date;

public class PostComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_comment.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_comment.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_comment.createdtime
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Date createdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_comment.comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_comment.commenttop
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer commenttop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_comment.postid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer postid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_comment.id
     *
     * @return the value of post_comment.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_comment.id
     *
     * @param id the value for post_comment.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_comment.userid
     *
     * @return the value of post_comment.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_comment.userid
     *
     * @param userid the value for post_comment.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_comment.createdtime
     *
     * @return the value of post_comment.createdtime
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Date getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_comment.createdtime
     *
     * @param createdtime the value for post_comment.createdtime
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_comment.comment
     *
     * @return the value of post_comment.comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_comment.comment
     *
     * @param comment the value for post_comment.comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_comment.commenttop
     *
     * @return the value of post_comment.commenttop
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getCommenttop() {
        return commenttop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_comment.commenttop
     *
     * @param commenttop the value for post_comment.commenttop
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCommenttop(Integer commenttop) {
        this.commenttop = commenttop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_comment.postid
     *
     * @return the value of post_comment.postid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_comment.postid
     *
     * @param postid the value for post_comment.postid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setPostid(Integer postid) {
        this.postid = postid;
    }
}