package com.shiyu.demo.entity;

public class RoleRoot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_root.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_root.role_id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_root.perms
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String perms;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_root.id
     *
     * @return the value of role_root.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_root.id
     *
     * @param id the value for role_root.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_root.role_id
     *
     * @return the value of role_root.role_id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_root.role_id
     *
     * @param roleId the value for role_root.role_id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_root.perms
     *
     * @return the value of role_root.perms
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_root.perms
     *
     * @param perms the value for role_root.perms
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setPerms(String perms) {
        this.perms = perms == null ? null : perms.trim();
    }
}