package com.shiyu.demo.entity;

import java.util.ArrayList;
import java.util.List;

public class ShopInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public ShopInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShopidIsNull() {
            addCriterion("shopid is null");
            return (Criteria) this;
        }

        public Criteria andShopidIsNotNull() {
            addCriterion("shopid is not null");
            return (Criteria) this;
        }

        public Criteria andShopidEqualTo(Integer value) {
            addCriterion("shopid =", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotEqualTo(Integer value) {
            addCriterion("shopid <>", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThan(Integer value) {
            addCriterion("shopid >", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopid >=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThan(Integer value) {
            addCriterion("shopid <", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThanOrEqualTo(Integer value) {
            addCriterion("shopid <=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidIn(List<Integer> values) {
            addCriterion("shopid in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotIn(List<Integer> values) {
            addCriterion("shopid not in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidBetween(Integer value1, Integer value2) {
            addCriterion("shopid between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotBetween(Integer value1, Integer value2) {
            addCriterion("shopid not between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andTasteIsNull() {
            addCriterion("taste is null");
            return (Criteria) this;
        }

        public Criteria andTasteIsNotNull() {
            addCriterion("taste is not null");
            return (Criteria) this;
        }

        public Criteria andTasteEqualTo(Integer value) {
            addCriterion("taste =", value, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteNotEqualTo(Integer value) {
            addCriterion("taste <>", value, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteGreaterThan(Integer value) {
            addCriterion("taste >", value, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteGreaterThanOrEqualTo(Integer value) {
            addCriterion("taste >=", value, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteLessThan(Integer value) {
            addCriterion("taste <", value, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteLessThanOrEqualTo(Integer value) {
            addCriterion("taste <=", value, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteIn(List<Integer> values) {
            addCriterion("taste in", values, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteNotIn(List<Integer> values) {
            addCriterion("taste not in", values, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteBetween(Integer value1, Integer value2) {
            addCriterion("taste between", value1, value2, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteNotBetween(Integer value1, Integer value2) {
            addCriterion("taste not between", value1, value2, "taste");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIsNull() {
            addCriterion("environment is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIsNotNull() {
            addCriterion("environment is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentEqualTo(Integer value) {
            addCriterion("environment =", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotEqualTo(Integer value) {
            addCriterion("environment <>", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentGreaterThan(Integer value) {
            addCriterion("environment >", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentGreaterThanOrEqualTo(Integer value) {
            addCriterion("environment >=", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentLessThan(Integer value) {
            addCriterion("environment <", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentLessThanOrEqualTo(Integer value) {
            addCriterion("environment <=", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIn(List<Integer> values) {
            addCriterion("environment in", values, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotIn(List<Integer> values) {
            addCriterion("environment not in", values, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentBetween(Integer value1, Integer value2) {
            addCriterion("environment between", value1, value2, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotBetween(Integer value1, Integer value2) {
            addCriterion("environment not between", value1, value2, "environment");
            return (Criteria) this;
        }

        public Criteria andServeIsNull() {
            addCriterion("serve is null");
            return (Criteria) this;
        }

        public Criteria andServeIsNotNull() {
            addCriterion("serve is not null");
            return (Criteria) this;
        }

        public Criteria andServeEqualTo(Integer value) {
            addCriterion("serve =", value, "serve");
            return (Criteria) this;
        }

        public Criteria andServeNotEqualTo(Integer value) {
            addCriterion("serve <>", value, "serve");
            return (Criteria) this;
        }

        public Criteria andServeGreaterThan(Integer value) {
            addCriterion("serve >", value, "serve");
            return (Criteria) this;
        }

        public Criteria andServeGreaterThanOrEqualTo(Integer value) {
            addCriterion("serve >=", value, "serve");
            return (Criteria) this;
        }

        public Criteria andServeLessThan(Integer value) {
            addCriterion("serve <", value, "serve");
            return (Criteria) this;
        }

        public Criteria andServeLessThanOrEqualTo(Integer value) {
            addCriterion("serve <=", value, "serve");
            return (Criteria) this;
        }

        public Criteria andServeIn(List<Integer> values) {
            addCriterion("serve in", values, "serve");
            return (Criteria) this;
        }

        public Criteria andServeNotIn(List<Integer> values) {
            addCriterion("serve not in", values, "serve");
            return (Criteria) this;
        }

        public Criteria andServeBetween(Integer value1, Integer value2) {
            addCriterion("serve between", value1, value2, "serve");
            return (Criteria) this;
        }

        public Criteria andServeNotBetween(Integer value1, Integer value2) {
            addCriterion("serve not between", value1, value2, "serve");
            return (Criteria) this;
        }

        public Criteria andFeatureIsNull() {
            addCriterion("feature is null");
            return (Criteria) this;
        }

        public Criteria andFeatureIsNotNull() {
            addCriterion("feature is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureEqualTo(Integer value) {
            addCriterion("feature =", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotEqualTo(Integer value) {
            addCriterion("feature <>", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureGreaterThan(Integer value) {
            addCriterion("feature >", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("feature >=", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureLessThan(Integer value) {
            addCriterion("feature <", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureLessThanOrEqualTo(Integer value) {
            addCriterion("feature <=", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureIn(List<Integer> values) {
            addCriterion("feature in", values, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotIn(List<Integer> values) {
            addCriterion("feature not in", values, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureBetween(Integer value1, Integer value2) {
            addCriterion("feature between", value1, value2, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotBetween(Integer value1, Integer value2) {
            addCriterion("feature not between", value1, value2, "feature");
            return (Criteria) this;
        }

        public Criteria andShoptypeIsNull() {
            addCriterion("shoptype is null");
            return (Criteria) this;
        }

        public Criteria andShoptypeIsNotNull() {
            addCriterion("shoptype is not null");
            return (Criteria) this;
        }

        public Criteria andShoptypeEqualTo(Integer value) {
            addCriterion("shoptype =", value, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeNotEqualTo(Integer value) {
            addCriterion("shoptype <>", value, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeGreaterThan(Integer value) {
            addCriterion("shoptype >", value, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("shoptype >=", value, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeLessThan(Integer value) {
            addCriterion("shoptype <", value, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeLessThanOrEqualTo(Integer value) {
            addCriterion("shoptype <=", value, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeIn(List<Integer> values) {
            addCriterion("shoptype in", values, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeNotIn(List<Integer> values) {
            addCriterion("shoptype not in", values, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeBetween(Integer value1, Integer value2) {
            addCriterion("shoptype between", value1, value2, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeNotBetween(Integer value1, Integer value2) {
            addCriterion("shoptype not between", value1, value2, "shoptype");
            return (Criteria) this;
        }

        public Criteria andSavesumIsNull() {
            addCriterion("savesum is null");
            return (Criteria) this;
        }

        public Criteria andSavesumIsNotNull() {
            addCriterion("savesum is not null");
            return (Criteria) this;
        }

        public Criteria andSavesumEqualTo(Integer value) {
            addCriterion("savesum =", value, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumNotEqualTo(Integer value) {
            addCriterion("savesum <>", value, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumGreaterThan(Integer value) {
            addCriterion("savesum >", value, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumGreaterThanOrEqualTo(Integer value) {
            addCriterion("savesum >=", value, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumLessThan(Integer value) {
            addCriterion("savesum <", value, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumLessThanOrEqualTo(Integer value) {
            addCriterion("savesum <=", value, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumIn(List<Integer> values) {
            addCriterion("savesum in", values, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumNotIn(List<Integer> values) {
            addCriterion("savesum not in", values, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumBetween(Integer value1, Integer value2) {
            addCriterion("savesum between", value1, value2, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumNotBetween(Integer value1, Integer value2) {
            addCriterion("savesum not between", value1, value2, "savesum");
            return (Criteria) this;
        }

        public Criteria andShopmanageIsNull() {
            addCriterion("shopmanage is null");
            return (Criteria) this;
        }

        public Criteria andShopmanageIsNotNull() {
            addCriterion("shopmanage is not null");
            return (Criteria) this;
        }

        public Criteria andShopmanageEqualTo(Integer value) {
            addCriterion("shopmanage =", value, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageNotEqualTo(Integer value) {
            addCriterion("shopmanage <>", value, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageGreaterThan(Integer value) {
            addCriterion("shopmanage >", value, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopmanage >=", value, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageLessThan(Integer value) {
            addCriterion("shopmanage <", value, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageLessThanOrEqualTo(Integer value) {
            addCriterion("shopmanage <=", value, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageIn(List<Integer> values) {
            addCriterion("shopmanage in", values, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageNotIn(List<Integer> values) {
            addCriterion("shopmanage not in", values, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageBetween(Integer value1, Integer value2) {
            addCriterion("shopmanage between", value1, value2, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageNotBetween(Integer value1, Integer value2) {
            addCriterion("shopmanage not between", value1, value2, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Long value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Long value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Long value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Long value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Long value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Long> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Long> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Long value1, Long value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Long value1, Long value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andCommentscoreIsNull() {
            addCriterion("commentscore is null");
            return (Criteria) this;
        }

        public Criteria andCommentscoreIsNotNull() {
            addCriterion("commentscore is not null");
            return (Criteria) this;
        }

        public Criteria andCommentscoreEqualTo(Integer value) {
            addCriterion("commentscore =", value, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreNotEqualTo(Integer value) {
            addCriterion("commentscore <>", value, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreGreaterThan(Integer value) {
            addCriterion("commentscore >", value, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("commentscore >=", value, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreLessThan(Integer value) {
            addCriterion("commentscore <", value, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreLessThanOrEqualTo(Integer value) {
            addCriterion("commentscore <=", value, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreIn(List<Integer> values) {
            addCriterion("commentscore in", values, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreNotIn(List<Integer> values) {
            addCriterion("commentscore not in", values, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreBetween(Integer value1, Integer value2) {
            addCriterion("commentscore between", value1, value2, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreNotBetween(Integer value1, Integer value2) {
            addCriterion("commentscore not between", value1, value2, "commentscore");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_info
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 26 19:29:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}