package com.shiyu.demo.entity;

public class ShopInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.taste
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer taste;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer environment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.serve
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer serve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.feature
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shoptype
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer shoptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.savesum
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer savesum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shopmanage
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer shopmanage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.price
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.commentscore
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer commentscore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shopid
     *
     * @return the value of shop_info.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shopid
     *
     * @param shopid the value for shop_info.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.taste
     *
     * @return the value of shop_info.taste
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getTaste() {
        return taste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.taste
     *
     * @param taste the value for shop_info.taste
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setTaste(Integer taste) {
        this.taste = taste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.environment
     *
     * @return the value of shop_info.environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getEnvironment() {
        return environment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.environment
     *
     * @param environment the value for shop_info.environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setEnvironment(Integer environment) {
        this.environment = environment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.serve
     *
     * @return the value of shop_info.serve
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getServe() {
        return serve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.serve
     *
     * @param serve the value for shop_info.serve
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setServe(Integer serve) {
        this.serve = serve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.feature
     *
     * @return the value of shop_info.feature
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.feature
     *
     * @param feature the value for shop_info.feature
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setFeature(Integer feature) {
        this.feature = feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shoptype
     *
     * @return the value of shop_info.shoptype
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getShoptype() {
        return shoptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shoptype
     *
     * @param shoptype the value for shop_info.shoptype
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShoptype(Integer shoptype) {
        this.shoptype = shoptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.savesum
     *
     * @return the value of shop_info.savesum
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getSavesum() {
        return savesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.savesum
     *
     * @param savesum the value for shop_info.savesum
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setSavesum(Integer savesum) {
        this.savesum = savesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shopmanage
     *
     * @return the value of shop_info.shopmanage
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getShopmanage() {
        return shopmanage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shopmanage
     *
     * @param shopmanage the value for shop_info.shopmanage
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopmanage(Integer shopmanage) {
        this.shopmanage = shopmanage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.price
     *
     * @return the value of shop_info.price
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.price
     *
     * @param price the value for shop_info.price
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.commentscore
     *
     * @return the value of shop_info.commentscore
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getCommentscore() {
        return commentscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.commentscore
     *
     * @param commentscore the value for shop_info.commentscore
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCommentscore(Integer commentscore) {
        this.commentscore = commentscore;
    }
}