package com.shiyu.demo.entity;

public class ShopLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.shopname
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String shopname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.shopads
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String shopads;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.shopphone
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String shopphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.shoppwd
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String shoppwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.business
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String business;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.frontcard
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String frontcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.countercard
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String countercard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.hyphoto
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String hyphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.taste
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer taste;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer environment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.serve
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer serve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.feature
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.shoptype
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer shoptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.savesum
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer savesum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.shopmanage
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer shopmanage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.price
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.commentscore
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer commentscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.shopadstype
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer shopadstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.avaImage
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String avaimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.legalname
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String legalname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.businessHours
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String businesshours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.shopheadimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String shopheadimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_log.code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.shopid
     *
     * @return the value of shop_log.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.shopid
     *
     * @param shopid the value for shop_log.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.shopname
     *
     * @return the value of shop_log.shopname
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.shopname
     *
     * @param shopname the value for shop_log.shopname
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.shopads
     *
     * @return the value of shop_log.shopads
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getShopads() {
        return shopads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.shopads
     *
     * @param shopads the value for shop_log.shopads
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopads(String shopads) {
        this.shopads = shopads == null ? null : shopads.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.shopphone
     *
     * @return the value of shop_log.shopphone
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getShopphone() {
        return shopphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.shopphone
     *
     * @param shopphone the value for shop_log.shopphone
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopphone(String shopphone) {
        this.shopphone = shopphone == null ? null : shopphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.shoppwd
     *
     * @return the value of shop_log.shoppwd
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getShoppwd() {
        return shoppwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.shoppwd
     *
     * @param shoppwd the value for shop_log.shoppwd
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShoppwd(String shoppwd) {
        this.shoppwd = shoppwd == null ? null : shoppwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.business
     *
     * @return the value of shop_log.business
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.business
     *
     * @param business the value for shop_log.business
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setBusiness(String business) {
        this.business = business == null ? null : business.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.frontcard
     *
     * @return the value of shop_log.frontcard
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getFrontcard() {
        return frontcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.frontcard
     *
     * @param frontcard the value for shop_log.frontcard
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setFrontcard(String frontcard) {
        this.frontcard = frontcard == null ? null : frontcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.countercard
     *
     * @return the value of shop_log.countercard
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getCountercard() {
        return countercard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.countercard
     *
     * @param countercard the value for shop_log.countercard
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCountercard(String countercard) {
        this.countercard = countercard == null ? null : countercard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.hyphoto
     *
     * @return the value of shop_log.hyphoto
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getHyphoto() {
        return hyphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.hyphoto
     *
     * @param hyphoto the value for shop_log.hyphoto
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setHyphoto(String hyphoto) {
        this.hyphoto = hyphoto == null ? null : hyphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.taste
     *
     * @return the value of shop_log.taste
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getTaste() {
        return taste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.taste
     *
     * @param taste the value for shop_log.taste
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setTaste(Integer taste) {
        this.taste = taste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.environment
     *
     * @return the value of shop_log.environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getEnvironment() {
        return environment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.environment
     *
     * @param environment the value for shop_log.environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setEnvironment(Integer environment) {
        this.environment = environment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.serve
     *
     * @return the value of shop_log.serve
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getServe() {
        return serve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.serve
     *
     * @param serve the value for shop_log.serve
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setServe(Integer serve) {
        this.serve = serve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.feature
     *
     * @return the value of shop_log.feature
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.feature
     *
     * @param feature the value for shop_log.feature
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setFeature(Integer feature) {
        this.feature = feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.shoptype
     *
     * @return the value of shop_log.shoptype
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getShoptype() {
        return shoptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.shoptype
     *
     * @param shoptype the value for shop_log.shoptype
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShoptype(Integer shoptype) {
        this.shoptype = shoptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.savesum
     *
     * @return the value of shop_log.savesum
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getSavesum() {
        return savesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.savesum
     *
     * @param savesum the value for shop_log.savesum
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setSavesum(Integer savesum) {
        this.savesum = savesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.shopmanage
     *
     * @return the value of shop_log.shopmanage
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getShopmanage() {
        return shopmanage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.shopmanage
     *
     * @param shopmanage the value for shop_log.shopmanage
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopmanage(Integer shopmanage) {
        this.shopmanage = shopmanage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.price
     *
     * @return the value of shop_log.price
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.price
     *
     * @param price the value for shop_log.price
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.commentscore
     *
     * @return the value of shop_log.commentscore
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getCommentscore() {
        return commentscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.commentscore
     *
     * @param commentscore the value for shop_log.commentscore
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCommentscore(Integer commentscore) {
        this.commentscore = commentscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.shopadstype
     *
     * @return the value of shop_log.shopadstype
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getShopadstype() {
        return shopadstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.shopadstype
     *
     * @param shopadstype the value for shop_log.shopadstype
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopadstype(Integer shopadstype) {
        this.shopadstype = shopadstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.avaImage
     *
     * @return the value of shop_log.avaImage
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getAvaimage() {
        return avaimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.avaImage
     *
     * @param avaimage the value for shop_log.avaImage
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setAvaimage(String avaimage) {
        this.avaimage = avaimage == null ? null : avaimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.legalname
     *
     * @return the value of shop_log.legalname
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getLegalname() {
        return legalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.legalname
     *
     * @param legalname the value for shop_log.legalname
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setLegalname(String legalname) {
        this.legalname = legalname == null ? null : legalname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.businessHours
     *
     * @return the value of shop_log.businessHours
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getBusinesshours() {
        return businesshours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.businessHours
     *
     * @param businesshours the value for shop_log.businessHours
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setBusinesshours(String businesshours) {
        this.businesshours = businesshours == null ? null : businesshours.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.shopheadimg
     *
     * @return the value of shop_log.shopheadimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getShopheadimg() {
        return shopheadimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.shopheadimg
     *
     * @param shopheadimg the value for shop_log.shopheadimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopheadimg(String shopheadimg) {
        this.shopheadimg = shopheadimg == null ? null : shopheadimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_log.code
     *
     * @return the value of shop_log.code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_log.code
     *
     * @param code the value for shop_log.code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}