package com.shiyu.demo.entity;

import java.util.ArrayList;
import java.util.List;

public class ShopLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public ShopLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShopidIsNull() {
            addCriterion("shopid is null");
            return (Criteria) this;
        }

        public Criteria andShopidIsNotNull() {
            addCriterion("shopid is not null");
            return (Criteria) this;
        }

        public Criteria andShopidEqualTo(Integer value) {
            addCriterion("shopid =", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotEqualTo(Integer value) {
            addCriterion("shopid <>", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThan(Integer value) {
            addCriterion("shopid >", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopid >=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThan(Integer value) {
            addCriterion("shopid <", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThanOrEqualTo(Integer value) {
            addCriterion("shopid <=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidIn(List<Integer> values) {
            addCriterion("shopid in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotIn(List<Integer> values) {
            addCriterion("shopid not in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidBetween(Integer value1, Integer value2) {
            addCriterion("shopid between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotBetween(Integer value1, Integer value2) {
            addCriterion("shopid not between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopnameIsNull() {
            addCriterion("shopname is null");
            return (Criteria) this;
        }

        public Criteria andShopnameIsNotNull() {
            addCriterion("shopname is not null");
            return (Criteria) this;
        }

        public Criteria andShopnameEqualTo(String value) {
            addCriterion("shopname =", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameNotEqualTo(String value) {
            addCriterion("shopname <>", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameGreaterThan(String value) {
            addCriterion("shopname >", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameGreaterThanOrEqualTo(String value) {
            addCriterion("shopname >=", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameLessThan(String value) {
            addCriterion("shopname <", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameLessThanOrEqualTo(String value) {
            addCriterion("shopname <=", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameLike(String value) {
            addCriterion("shopname like", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameNotLike(String value) {
            addCriterion("shopname not like", value, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameIn(List<String> values) {
            addCriterion("shopname in", values, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameNotIn(List<String> values) {
            addCriterion("shopname not in", values, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameBetween(String value1, String value2) {
            addCriterion("shopname between", value1, value2, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopnameNotBetween(String value1, String value2) {
            addCriterion("shopname not between", value1, value2, "shopname");
            return (Criteria) this;
        }

        public Criteria andShopadsIsNull() {
            addCriterion("shopads is null");
            return (Criteria) this;
        }

        public Criteria andShopadsIsNotNull() {
            addCriterion("shopads is not null");
            return (Criteria) this;
        }

        public Criteria andShopadsEqualTo(String value) {
            addCriterion("shopads =", value, "shopads");
            return (Criteria) this;
        }

        public Criteria andShopadsNotEqualTo(String value) {
            addCriterion("shopads <>", value, "shopads");
            return (Criteria) this;
        }

        public Criteria andShopadsGreaterThan(String value) {
            addCriterion("shopads >", value, "shopads");
            return (Criteria) this;
        }

        public Criteria andShopadsGreaterThanOrEqualTo(String value) {
            addCriterion("shopads >=", value, "shopads");
            return (Criteria) this;
        }

        public Criteria andShopadsLessThan(String value) {
            addCriterion("shopads <", value, "shopads");
            return (Criteria) this;
        }

        public Criteria andShopadsLessThanOrEqualTo(String value) {
            addCriterion("shopads <=", value, "shopads");
            return (Criteria) this;
        }

        public Criteria andShopadsLike(String value) {
            addCriterion("shopads like", value, "shopads");
            return (Criteria) this;
        }

        public Criteria andShopadsNotLike(String value) {
            addCriterion("shopads not like", value, "shopads");
            return (Criteria) this;
        }

        public Criteria andShopadsIn(List<String> values) {
            addCriterion("shopads in", values, "shopads");
            return (Criteria) this;
        }

        public Criteria andShopadsNotIn(List<String> values) {
            addCriterion("shopads not in", values, "shopads");
            return (Criteria) this;
        }

        public Criteria andShopadsBetween(String value1, String value2) {
            addCriterion("shopads between", value1, value2, "shopads");
            return (Criteria) this;
        }

        public Criteria andShopadsNotBetween(String value1, String value2) {
            addCriterion("shopads not between", value1, value2, "shopads");
            return (Criteria) this;
        }

        public Criteria andShopphoneIsNull() {
            addCriterion("shopphone is null");
            return (Criteria) this;
        }

        public Criteria andShopphoneIsNotNull() {
            addCriterion("shopphone is not null");
            return (Criteria) this;
        }

        public Criteria andShopphoneEqualTo(String value) {
            addCriterion("shopphone =", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneNotEqualTo(String value) {
            addCriterion("shopphone <>", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneGreaterThan(String value) {
            addCriterion("shopphone >", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneGreaterThanOrEqualTo(String value) {
            addCriterion("shopphone >=", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneLessThan(String value) {
            addCriterion("shopphone <", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneLessThanOrEqualTo(String value) {
            addCriterion("shopphone <=", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneLike(String value) {
            addCriterion("shopphone like", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneNotLike(String value) {
            addCriterion("shopphone not like", value, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneIn(List<String> values) {
            addCriterion("shopphone in", values, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneNotIn(List<String> values) {
            addCriterion("shopphone not in", values, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneBetween(String value1, String value2) {
            addCriterion("shopphone between", value1, value2, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShopphoneNotBetween(String value1, String value2) {
            addCriterion("shopphone not between", value1, value2, "shopphone");
            return (Criteria) this;
        }

        public Criteria andShoppwdIsNull() {
            addCriterion("shoppwd is null");
            return (Criteria) this;
        }

        public Criteria andShoppwdIsNotNull() {
            addCriterion("shoppwd is not null");
            return (Criteria) this;
        }

        public Criteria andShoppwdEqualTo(String value) {
            addCriterion("shoppwd =", value, "shoppwd");
            return (Criteria) this;
        }

        public Criteria andShoppwdNotEqualTo(String value) {
            addCriterion("shoppwd <>", value, "shoppwd");
            return (Criteria) this;
        }

        public Criteria andShoppwdGreaterThan(String value) {
            addCriterion("shoppwd >", value, "shoppwd");
            return (Criteria) this;
        }

        public Criteria andShoppwdGreaterThanOrEqualTo(String value) {
            addCriterion("shoppwd >=", value, "shoppwd");
            return (Criteria) this;
        }

        public Criteria andShoppwdLessThan(String value) {
            addCriterion("shoppwd <", value, "shoppwd");
            return (Criteria) this;
        }

        public Criteria andShoppwdLessThanOrEqualTo(String value) {
            addCriterion("shoppwd <=", value, "shoppwd");
            return (Criteria) this;
        }

        public Criteria andShoppwdLike(String value) {
            addCriterion("shoppwd like", value, "shoppwd");
            return (Criteria) this;
        }

        public Criteria andShoppwdNotLike(String value) {
            addCriterion("shoppwd not like", value, "shoppwd");
            return (Criteria) this;
        }

        public Criteria andShoppwdIn(List<String> values) {
            addCriterion("shoppwd in", values, "shoppwd");
            return (Criteria) this;
        }

        public Criteria andShoppwdNotIn(List<String> values) {
            addCriterion("shoppwd not in", values, "shoppwd");
            return (Criteria) this;
        }

        public Criteria andShoppwdBetween(String value1, String value2) {
            addCriterion("shoppwd between", value1, value2, "shoppwd");
            return (Criteria) this;
        }

        public Criteria andShoppwdNotBetween(String value1, String value2) {
            addCriterion("shoppwd not between", value1, value2, "shoppwd");
            return (Criteria) this;
        }

        public Criteria andBusinessIsNull() {
            addCriterion("business is null");
            return (Criteria) this;
        }

        public Criteria andBusinessIsNotNull() {
            addCriterion("business is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessEqualTo(String value) {
            addCriterion("business =", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessNotEqualTo(String value) {
            addCriterion("business <>", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessGreaterThan(String value) {
            addCriterion("business >", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessGreaterThanOrEqualTo(String value) {
            addCriterion("business >=", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessLessThan(String value) {
            addCriterion("business <", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessLessThanOrEqualTo(String value) {
            addCriterion("business <=", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessLike(String value) {
            addCriterion("business like", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessNotLike(String value) {
            addCriterion("business not like", value, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessIn(List<String> values) {
            addCriterion("business in", values, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessNotIn(List<String> values) {
            addCriterion("business not in", values, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessBetween(String value1, String value2) {
            addCriterion("business between", value1, value2, "business");
            return (Criteria) this;
        }

        public Criteria andBusinessNotBetween(String value1, String value2) {
            addCriterion("business not between", value1, value2, "business");
            return (Criteria) this;
        }

        public Criteria andFrontcardIsNull() {
            addCriterion("frontcard is null");
            return (Criteria) this;
        }

        public Criteria andFrontcardIsNotNull() {
            addCriterion("frontcard is not null");
            return (Criteria) this;
        }

        public Criteria andFrontcardEqualTo(String value) {
            addCriterion("frontcard =", value, "frontcard");
            return (Criteria) this;
        }

        public Criteria andFrontcardNotEqualTo(String value) {
            addCriterion("frontcard <>", value, "frontcard");
            return (Criteria) this;
        }

        public Criteria andFrontcardGreaterThan(String value) {
            addCriterion("frontcard >", value, "frontcard");
            return (Criteria) this;
        }

        public Criteria andFrontcardGreaterThanOrEqualTo(String value) {
            addCriterion("frontcard >=", value, "frontcard");
            return (Criteria) this;
        }

        public Criteria andFrontcardLessThan(String value) {
            addCriterion("frontcard <", value, "frontcard");
            return (Criteria) this;
        }

        public Criteria andFrontcardLessThanOrEqualTo(String value) {
            addCriterion("frontcard <=", value, "frontcard");
            return (Criteria) this;
        }

        public Criteria andFrontcardLike(String value) {
            addCriterion("frontcard like", value, "frontcard");
            return (Criteria) this;
        }

        public Criteria andFrontcardNotLike(String value) {
            addCriterion("frontcard not like", value, "frontcard");
            return (Criteria) this;
        }

        public Criteria andFrontcardIn(List<String> values) {
            addCriterion("frontcard in", values, "frontcard");
            return (Criteria) this;
        }

        public Criteria andFrontcardNotIn(List<String> values) {
            addCriterion("frontcard not in", values, "frontcard");
            return (Criteria) this;
        }

        public Criteria andFrontcardBetween(String value1, String value2) {
            addCriterion("frontcard between", value1, value2, "frontcard");
            return (Criteria) this;
        }

        public Criteria andFrontcardNotBetween(String value1, String value2) {
            addCriterion("frontcard not between", value1, value2, "frontcard");
            return (Criteria) this;
        }

        public Criteria andCountercardIsNull() {
            addCriterion("countercard is null");
            return (Criteria) this;
        }

        public Criteria andCountercardIsNotNull() {
            addCriterion("countercard is not null");
            return (Criteria) this;
        }

        public Criteria andCountercardEqualTo(String value) {
            addCriterion("countercard =", value, "countercard");
            return (Criteria) this;
        }

        public Criteria andCountercardNotEqualTo(String value) {
            addCriterion("countercard <>", value, "countercard");
            return (Criteria) this;
        }

        public Criteria andCountercardGreaterThan(String value) {
            addCriterion("countercard >", value, "countercard");
            return (Criteria) this;
        }

        public Criteria andCountercardGreaterThanOrEqualTo(String value) {
            addCriterion("countercard >=", value, "countercard");
            return (Criteria) this;
        }

        public Criteria andCountercardLessThan(String value) {
            addCriterion("countercard <", value, "countercard");
            return (Criteria) this;
        }

        public Criteria andCountercardLessThanOrEqualTo(String value) {
            addCriterion("countercard <=", value, "countercard");
            return (Criteria) this;
        }

        public Criteria andCountercardLike(String value) {
            addCriterion("countercard like", value, "countercard");
            return (Criteria) this;
        }

        public Criteria andCountercardNotLike(String value) {
            addCriterion("countercard not like", value, "countercard");
            return (Criteria) this;
        }

        public Criteria andCountercardIn(List<String> values) {
            addCriterion("countercard in", values, "countercard");
            return (Criteria) this;
        }

        public Criteria andCountercardNotIn(List<String> values) {
            addCriterion("countercard not in", values, "countercard");
            return (Criteria) this;
        }

        public Criteria andCountercardBetween(String value1, String value2) {
            addCriterion("countercard between", value1, value2, "countercard");
            return (Criteria) this;
        }

        public Criteria andCountercardNotBetween(String value1, String value2) {
            addCriterion("countercard not between", value1, value2, "countercard");
            return (Criteria) this;
        }

        public Criteria andHyphotoIsNull() {
            addCriterion("hyphoto is null");
            return (Criteria) this;
        }

        public Criteria andHyphotoIsNotNull() {
            addCriterion("hyphoto is not null");
            return (Criteria) this;
        }

        public Criteria andHyphotoEqualTo(String value) {
            addCriterion("hyphoto =", value, "hyphoto");
            return (Criteria) this;
        }

        public Criteria andHyphotoNotEqualTo(String value) {
            addCriterion("hyphoto <>", value, "hyphoto");
            return (Criteria) this;
        }

        public Criteria andHyphotoGreaterThan(String value) {
            addCriterion("hyphoto >", value, "hyphoto");
            return (Criteria) this;
        }

        public Criteria andHyphotoGreaterThanOrEqualTo(String value) {
            addCriterion("hyphoto >=", value, "hyphoto");
            return (Criteria) this;
        }

        public Criteria andHyphotoLessThan(String value) {
            addCriterion("hyphoto <", value, "hyphoto");
            return (Criteria) this;
        }

        public Criteria andHyphotoLessThanOrEqualTo(String value) {
            addCriterion("hyphoto <=", value, "hyphoto");
            return (Criteria) this;
        }

        public Criteria andHyphotoLike(String value) {
            addCriterion("hyphoto like", value, "hyphoto");
            return (Criteria) this;
        }

        public Criteria andHyphotoNotLike(String value) {
            addCriterion("hyphoto not like", value, "hyphoto");
            return (Criteria) this;
        }

        public Criteria andHyphotoIn(List<String> values) {
            addCriterion("hyphoto in", values, "hyphoto");
            return (Criteria) this;
        }

        public Criteria andHyphotoNotIn(List<String> values) {
            addCriterion("hyphoto not in", values, "hyphoto");
            return (Criteria) this;
        }

        public Criteria andHyphotoBetween(String value1, String value2) {
            addCriterion("hyphoto between", value1, value2, "hyphoto");
            return (Criteria) this;
        }

        public Criteria andHyphotoNotBetween(String value1, String value2) {
            addCriterion("hyphoto not between", value1, value2, "hyphoto");
            return (Criteria) this;
        }

        public Criteria andTasteIsNull() {
            addCriterion("taste is null");
            return (Criteria) this;
        }

        public Criteria andTasteIsNotNull() {
            addCriterion("taste is not null");
            return (Criteria) this;
        }

        public Criteria andTasteEqualTo(Integer value) {
            addCriterion("taste =", value, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteNotEqualTo(Integer value) {
            addCriterion("taste <>", value, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteGreaterThan(Integer value) {
            addCriterion("taste >", value, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteGreaterThanOrEqualTo(Integer value) {
            addCriterion("taste >=", value, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteLessThan(Integer value) {
            addCriterion("taste <", value, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteLessThanOrEqualTo(Integer value) {
            addCriterion("taste <=", value, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteIn(List<Integer> values) {
            addCriterion("taste in", values, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteNotIn(List<Integer> values) {
            addCriterion("taste not in", values, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteBetween(Integer value1, Integer value2) {
            addCriterion("taste between", value1, value2, "taste");
            return (Criteria) this;
        }

        public Criteria andTasteNotBetween(Integer value1, Integer value2) {
            addCriterion("taste not between", value1, value2, "taste");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIsNull() {
            addCriterion("environment is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIsNotNull() {
            addCriterion("environment is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentEqualTo(Integer value) {
            addCriterion("environment =", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotEqualTo(Integer value) {
            addCriterion("environment <>", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentGreaterThan(Integer value) {
            addCriterion("environment >", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentGreaterThanOrEqualTo(Integer value) {
            addCriterion("environment >=", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentLessThan(Integer value) {
            addCriterion("environment <", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentLessThanOrEqualTo(Integer value) {
            addCriterion("environment <=", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIn(List<Integer> values) {
            addCriterion("environment in", values, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotIn(List<Integer> values) {
            addCriterion("environment not in", values, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentBetween(Integer value1, Integer value2) {
            addCriterion("environment between", value1, value2, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotBetween(Integer value1, Integer value2) {
            addCriterion("environment not between", value1, value2, "environment");
            return (Criteria) this;
        }

        public Criteria andServeIsNull() {
            addCriterion("serve is null");
            return (Criteria) this;
        }

        public Criteria andServeIsNotNull() {
            addCriterion("serve is not null");
            return (Criteria) this;
        }

        public Criteria andServeEqualTo(Integer value) {
            addCriterion("serve =", value, "serve");
            return (Criteria) this;
        }

        public Criteria andServeNotEqualTo(Integer value) {
            addCriterion("serve <>", value, "serve");
            return (Criteria) this;
        }

        public Criteria andServeGreaterThan(Integer value) {
            addCriterion("serve >", value, "serve");
            return (Criteria) this;
        }

        public Criteria andServeGreaterThanOrEqualTo(Integer value) {
            addCriterion("serve >=", value, "serve");
            return (Criteria) this;
        }

        public Criteria andServeLessThan(Integer value) {
            addCriterion("serve <", value, "serve");
            return (Criteria) this;
        }

        public Criteria andServeLessThanOrEqualTo(Integer value) {
            addCriterion("serve <=", value, "serve");
            return (Criteria) this;
        }

        public Criteria andServeIn(List<Integer> values) {
            addCriterion("serve in", values, "serve");
            return (Criteria) this;
        }

        public Criteria andServeNotIn(List<Integer> values) {
            addCriterion("serve not in", values, "serve");
            return (Criteria) this;
        }

        public Criteria andServeBetween(Integer value1, Integer value2) {
            addCriterion("serve between", value1, value2, "serve");
            return (Criteria) this;
        }

        public Criteria andServeNotBetween(Integer value1, Integer value2) {
            addCriterion("serve not between", value1, value2, "serve");
            return (Criteria) this;
        }

        public Criteria andFeatureIsNull() {
            addCriterion("feature is null");
            return (Criteria) this;
        }

        public Criteria andFeatureIsNotNull() {
            addCriterion("feature is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureEqualTo(Integer value) {
            addCriterion("feature =", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotEqualTo(Integer value) {
            addCriterion("feature <>", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureGreaterThan(Integer value) {
            addCriterion("feature >", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("feature >=", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureLessThan(Integer value) {
            addCriterion("feature <", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureLessThanOrEqualTo(Integer value) {
            addCriterion("feature <=", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureIn(List<Integer> values) {
            addCriterion("feature in", values, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotIn(List<Integer> values) {
            addCriterion("feature not in", values, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureBetween(Integer value1, Integer value2) {
            addCriterion("feature between", value1, value2, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotBetween(Integer value1, Integer value2) {
            addCriterion("feature not between", value1, value2, "feature");
            return (Criteria) this;
        }

        public Criteria andShoptypeIsNull() {
            addCriterion("shoptype is null");
            return (Criteria) this;
        }

        public Criteria andShoptypeIsNotNull() {
            addCriterion("shoptype is not null");
            return (Criteria) this;
        }

        public Criteria andShoptypeEqualTo(Integer value) {
            addCriterion("shoptype =", value, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeNotEqualTo(Integer value) {
            addCriterion("shoptype <>", value, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeGreaterThan(Integer value) {
            addCriterion("shoptype >", value, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("shoptype >=", value, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeLessThan(Integer value) {
            addCriterion("shoptype <", value, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeLessThanOrEqualTo(Integer value) {
            addCriterion("shoptype <=", value, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeIn(List<Integer> values) {
            addCriterion("shoptype in", values, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeNotIn(List<Integer> values) {
            addCriterion("shoptype not in", values, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeBetween(Integer value1, Integer value2) {
            addCriterion("shoptype between", value1, value2, "shoptype");
            return (Criteria) this;
        }

        public Criteria andShoptypeNotBetween(Integer value1, Integer value2) {
            addCriterion("shoptype not between", value1, value2, "shoptype");
            return (Criteria) this;
        }

        public Criteria andSavesumIsNull() {
            addCriterion("savesum is null");
            return (Criteria) this;
        }

        public Criteria andSavesumIsNotNull() {
            addCriterion("savesum is not null");
            return (Criteria) this;
        }

        public Criteria andSavesumEqualTo(Integer value) {
            addCriterion("savesum =", value, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumNotEqualTo(Integer value) {
            addCriterion("savesum <>", value, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumGreaterThan(Integer value) {
            addCriterion("savesum >", value, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumGreaterThanOrEqualTo(Integer value) {
            addCriterion("savesum >=", value, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumLessThan(Integer value) {
            addCriterion("savesum <", value, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumLessThanOrEqualTo(Integer value) {
            addCriterion("savesum <=", value, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumIn(List<Integer> values) {
            addCriterion("savesum in", values, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumNotIn(List<Integer> values) {
            addCriterion("savesum not in", values, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumBetween(Integer value1, Integer value2) {
            addCriterion("savesum between", value1, value2, "savesum");
            return (Criteria) this;
        }

        public Criteria andSavesumNotBetween(Integer value1, Integer value2) {
            addCriterion("savesum not between", value1, value2, "savesum");
            return (Criteria) this;
        }

        public Criteria andShopmanageIsNull() {
            addCriterion("shopmanage is null");
            return (Criteria) this;
        }

        public Criteria andShopmanageIsNotNull() {
            addCriterion("shopmanage is not null");
            return (Criteria) this;
        }

        public Criteria andShopmanageEqualTo(Integer value) {
            addCriterion("shopmanage =", value, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageNotEqualTo(Integer value) {
            addCriterion("shopmanage <>", value, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageGreaterThan(Integer value) {
            addCriterion("shopmanage >", value, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopmanage >=", value, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageLessThan(Integer value) {
            addCriterion("shopmanage <", value, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageLessThanOrEqualTo(Integer value) {
            addCriterion("shopmanage <=", value, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageIn(List<Integer> values) {
            addCriterion("shopmanage in", values, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageNotIn(List<Integer> values) {
            addCriterion("shopmanage not in", values, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageBetween(Integer value1, Integer value2) {
            addCriterion("shopmanage between", value1, value2, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andShopmanageNotBetween(Integer value1, Integer value2) {
            addCriterion("shopmanage not between", value1, value2, "shopmanage");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Long value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Long value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Long value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Long value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Long value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Long> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Long> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Long value1, Long value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Long value1, Long value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andCommentscoreIsNull() {
            addCriterion("commentscore is null");
            return (Criteria) this;
        }

        public Criteria andCommentscoreIsNotNull() {
            addCriterion("commentscore is not null");
            return (Criteria) this;
        }

        public Criteria andCommentscoreEqualTo(Integer value) {
            addCriterion("commentscore =", value, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreNotEqualTo(Integer value) {
            addCriterion("commentscore <>", value, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreGreaterThan(Integer value) {
            addCriterion("commentscore >", value, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("commentscore >=", value, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreLessThan(Integer value) {
            addCriterion("commentscore <", value, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreLessThanOrEqualTo(Integer value) {
            addCriterion("commentscore <=", value, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreIn(List<Integer> values) {
            addCriterion("commentscore in", values, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreNotIn(List<Integer> values) {
            addCriterion("commentscore not in", values, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreBetween(Integer value1, Integer value2) {
            addCriterion("commentscore between", value1, value2, "commentscore");
            return (Criteria) this;
        }

        public Criteria andCommentscoreNotBetween(Integer value1, Integer value2) {
            addCriterion("commentscore not between", value1, value2, "commentscore");
            return (Criteria) this;
        }

        public Criteria andShopadstypeIsNull() {
            addCriterion("shopadstype is null");
            return (Criteria) this;
        }

        public Criteria andShopadstypeIsNotNull() {
            addCriterion("shopadstype is not null");
            return (Criteria) this;
        }

        public Criteria andShopadstypeEqualTo(Integer value) {
            addCriterion("shopadstype =", value, "shopadstype");
            return (Criteria) this;
        }

        public Criteria andShopadstypeNotEqualTo(Integer value) {
            addCriterion("shopadstype <>", value, "shopadstype");
            return (Criteria) this;
        }

        public Criteria andShopadstypeGreaterThan(Integer value) {
            addCriterion("shopadstype >", value, "shopadstype");
            return (Criteria) this;
        }

        public Criteria andShopadstypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopadstype >=", value, "shopadstype");
            return (Criteria) this;
        }

        public Criteria andShopadstypeLessThan(Integer value) {
            addCriterion("shopadstype <", value, "shopadstype");
            return (Criteria) this;
        }

        public Criteria andShopadstypeLessThanOrEqualTo(Integer value) {
            addCriterion("shopadstype <=", value, "shopadstype");
            return (Criteria) this;
        }

        public Criteria andShopadstypeIn(List<Integer> values) {
            addCriterion("shopadstype in", values, "shopadstype");
            return (Criteria) this;
        }

        public Criteria andShopadstypeNotIn(List<Integer> values) {
            addCriterion("shopadstype not in", values, "shopadstype");
            return (Criteria) this;
        }

        public Criteria andShopadstypeBetween(Integer value1, Integer value2) {
            addCriterion("shopadstype between", value1, value2, "shopadstype");
            return (Criteria) this;
        }

        public Criteria andShopadstypeNotBetween(Integer value1, Integer value2) {
            addCriterion("shopadstype not between", value1, value2, "shopadstype");
            return (Criteria) this;
        }

        public Criteria andAvaimageIsNull() {
            addCriterion("avaImage is null");
            return (Criteria) this;
        }

        public Criteria andAvaimageIsNotNull() {
            addCriterion("avaImage is not null");
            return (Criteria) this;
        }

        public Criteria andAvaimageEqualTo(String value) {
            addCriterion("avaImage =", value, "avaimage");
            return (Criteria) this;
        }

        public Criteria andAvaimageNotEqualTo(String value) {
            addCriterion("avaImage <>", value, "avaimage");
            return (Criteria) this;
        }

        public Criteria andAvaimageGreaterThan(String value) {
            addCriterion("avaImage >", value, "avaimage");
            return (Criteria) this;
        }

        public Criteria andAvaimageGreaterThanOrEqualTo(String value) {
            addCriterion("avaImage >=", value, "avaimage");
            return (Criteria) this;
        }

        public Criteria andAvaimageLessThan(String value) {
            addCriterion("avaImage <", value, "avaimage");
            return (Criteria) this;
        }

        public Criteria andAvaimageLessThanOrEqualTo(String value) {
            addCriterion("avaImage <=", value, "avaimage");
            return (Criteria) this;
        }

        public Criteria andAvaimageLike(String value) {
            addCriterion("avaImage like", value, "avaimage");
            return (Criteria) this;
        }

        public Criteria andAvaimageNotLike(String value) {
            addCriterion("avaImage not like", value, "avaimage");
            return (Criteria) this;
        }

        public Criteria andAvaimageIn(List<String> values) {
            addCriterion("avaImage in", values, "avaimage");
            return (Criteria) this;
        }

        public Criteria andAvaimageNotIn(List<String> values) {
            addCriterion("avaImage not in", values, "avaimage");
            return (Criteria) this;
        }

        public Criteria andAvaimageBetween(String value1, String value2) {
            addCriterion("avaImage between", value1, value2, "avaimage");
            return (Criteria) this;
        }

        public Criteria andAvaimageNotBetween(String value1, String value2) {
            addCriterion("avaImage not between", value1, value2, "avaimage");
            return (Criteria) this;
        }

        public Criteria andLegalnameIsNull() {
            addCriterion("legalname is null");
            return (Criteria) this;
        }

        public Criteria andLegalnameIsNotNull() {
            addCriterion("legalname is not null");
            return (Criteria) this;
        }

        public Criteria andLegalnameEqualTo(String value) {
            addCriterion("legalname =", value, "legalname");
            return (Criteria) this;
        }

        public Criteria andLegalnameNotEqualTo(String value) {
            addCriterion("legalname <>", value, "legalname");
            return (Criteria) this;
        }

        public Criteria andLegalnameGreaterThan(String value) {
            addCriterion("legalname >", value, "legalname");
            return (Criteria) this;
        }

        public Criteria andLegalnameGreaterThanOrEqualTo(String value) {
            addCriterion("legalname >=", value, "legalname");
            return (Criteria) this;
        }

        public Criteria andLegalnameLessThan(String value) {
            addCriterion("legalname <", value, "legalname");
            return (Criteria) this;
        }

        public Criteria andLegalnameLessThanOrEqualTo(String value) {
            addCriterion("legalname <=", value, "legalname");
            return (Criteria) this;
        }

        public Criteria andLegalnameLike(String value) {
            addCriterion("legalname like", value, "legalname");
            return (Criteria) this;
        }

        public Criteria andLegalnameNotLike(String value) {
            addCriterion("legalname not like", value, "legalname");
            return (Criteria) this;
        }

        public Criteria andLegalnameIn(List<String> values) {
            addCriterion("legalname in", values, "legalname");
            return (Criteria) this;
        }

        public Criteria andLegalnameNotIn(List<String> values) {
            addCriterion("legalname not in", values, "legalname");
            return (Criteria) this;
        }

        public Criteria andLegalnameBetween(String value1, String value2) {
            addCriterion("legalname between", value1, value2, "legalname");
            return (Criteria) this;
        }

        public Criteria andLegalnameNotBetween(String value1, String value2) {
            addCriterion("legalname not between", value1, value2, "legalname");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursIsNull() {
            addCriterion("businessHours is null");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursIsNotNull() {
            addCriterion("businessHours is not null");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursEqualTo(String value) {
            addCriterion("businessHours =", value, "businesshours");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursNotEqualTo(String value) {
            addCriterion("businessHours <>", value, "businesshours");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursGreaterThan(String value) {
            addCriterion("businessHours >", value, "businesshours");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursGreaterThanOrEqualTo(String value) {
            addCriterion("businessHours >=", value, "businesshours");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursLessThan(String value) {
            addCriterion("businessHours <", value, "businesshours");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursLessThanOrEqualTo(String value) {
            addCriterion("businessHours <=", value, "businesshours");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursLike(String value) {
            addCriterion("businessHours like", value, "businesshours");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursNotLike(String value) {
            addCriterion("businessHours not like", value, "businesshours");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursIn(List<String> values) {
            addCriterion("businessHours in", values, "businesshours");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursNotIn(List<String> values) {
            addCriterion("businessHours not in", values, "businesshours");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursBetween(String value1, String value2) {
            addCriterion("businessHours between", value1, value2, "businesshours");
            return (Criteria) this;
        }

        public Criteria andBusinesshoursNotBetween(String value1, String value2) {
            addCriterion("businessHours not between", value1, value2, "businesshours");
            return (Criteria) this;
        }

        public Criteria andShopheadimgIsNull() {
            addCriterion("shopheadimg is null");
            return (Criteria) this;
        }

        public Criteria andShopheadimgIsNotNull() {
            addCriterion("shopheadimg is not null");
            return (Criteria) this;
        }

        public Criteria andShopheadimgEqualTo(String value) {
            addCriterion("shopheadimg =", value, "shopheadimg");
            return (Criteria) this;
        }

        public Criteria andShopheadimgNotEqualTo(String value) {
            addCriterion("shopheadimg <>", value, "shopheadimg");
            return (Criteria) this;
        }

        public Criteria andShopheadimgGreaterThan(String value) {
            addCriterion("shopheadimg >", value, "shopheadimg");
            return (Criteria) this;
        }

        public Criteria andShopheadimgGreaterThanOrEqualTo(String value) {
            addCriterion("shopheadimg >=", value, "shopheadimg");
            return (Criteria) this;
        }

        public Criteria andShopheadimgLessThan(String value) {
            addCriterion("shopheadimg <", value, "shopheadimg");
            return (Criteria) this;
        }

        public Criteria andShopheadimgLessThanOrEqualTo(String value) {
            addCriterion("shopheadimg <=", value, "shopheadimg");
            return (Criteria) this;
        }

        public Criteria andShopheadimgLike(String value) {
            addCriterion("shopheadimg like", value, "shopheadimg");
            return (Criteria) this;
        }

        public Criteria andShopheadimgNotLike(String value) {
            addCriterion("shopheadimg not like", value, "shopheadimg");
            return (Criteria) this;
        }

        public Criteria andShopheadimgIn(List<String> values) {
            addCriterion("shopheadimg in", values, "shopheadimg");
            return (Criteria) this;
        }

        public Criteria andShopheadimgNotIn(List<String> values) {
            addCriterion("shopheadimg not in", values, "shopheadimg");
            return (Criteria) this;
        }

        public Criteria andShopheadimgBetween(String value1, String value2) {
            addCriterion("shopheadimg between", value1, value2, "shopheadimg");
            return (Criteria) this;
        }

        public Criteria andShopheadimgNotBetween(String value1, String value2) {
            addCriterion("shopheadimg not between", value1, value2, "shopheadimg");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_log
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 26 19:29:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}