package com.shiyu.demo.entity;

public class ShopPhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_photo.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_photo.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_photo.shopphoto_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String shopphotoImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_photo.id
     *
     * @return the value of shop_photo.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_photo.id
     *
     * @param id the value for shop_photo.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_photo.shopid
     *
     * @return the value of shop_photo.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_photo.shopid
     *
     * @param shopid the value for shop_photo.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_photo.shopphoto_img
     *
     * @return the value of shop_photo.shopphoto_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getShopphotoImg() {
        return shopphotoImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_photo.shopphoto_img
     *
     * @param shopphotoImg the value for shop_photo.shopphoto_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopphotoImg(String shopphotoImg) {
        this.shopphotoImg = shopphotoImg == null ? null : shopphotoImg.trim();
    }
}