package com.shiyu.demo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ShopTicket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_ticket.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_ticket.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_ticket.ticketinfo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String ticketinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_ticket.price
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_ticket.rackrate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private BigDecimal rackrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_ticket.numberofsold
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer numberofsold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_ticket.craeteddate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Date craeteddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_ticket.score
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_ticket.commentsum
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer commentsum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_ticket.overtime
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Date overtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_ticket.ticketname
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String ticketname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_ticket.ticketimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String ticketimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_ticket.id
     *
     * @return the value of shop_ticket.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_ticket.id
     *
     * @param id the value for shop_ticket.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_ticket.shopid
     *
     * @return the value of shop_ticket.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_ticket.shopid
     *
     * @param shopid the value for shop_ticket.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_ticket.ticketinfo
     *
     * @return the value of shop_ticket.ticketinfo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getTicketinfo() {
        return ticketinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_ticket.ticketinfo
     *
     * @param ticketinfo the value for shop_ticket.ticketinfo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setTicketinfo(String ticketinfo) {
        this.ticketinfo = ticketinfo == null ? null : ticketinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_ticket.price
     *
     * @return the value of shop_ticket.price
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_ticket.price
     *
     * @param price the value for shop_ticket.price
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_ticket.rackrate
     *
     * @return the value of shop_ticket.rackrate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public BigDecimal getRackrate() {
        return rackrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_ticket.rackrate
     *
     * @param rackrate the value for shop_ticket.rackrate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setRackrate(BigDecimal rackrate) {
        this.rackrate = rackrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_ticket.numberofsold
     *
     * @return the value of shop_ticket.numberofsold
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getNumberofsold() {
        return numberofsold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_ticket.numberofsold
     *
     * @param numberofsold the value for shop_ticket.numberofsold
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setNumberofsold(Integer numberofsold) {
        this.numberofsold = numberofsold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_ticket.craeteddate
     *
     * @return the value of shop_ticket.craeteddate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Date getCraeteddate() {
        return craeteddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_ticket.craeteddate
     *
     * @param craeteddate the value for shop_ticket.craeteddate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCraeteddate(Date craeteddate) {
        this.craeteddate = craeteddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_ticket.score
     *
     * @return the value of shop_ticket.score
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_ticket.score
     *
     * @param score the value for shop_ticket.score
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_ticket.commentsum
     *
     * @return the value of shop_ticket.commentsum
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getCommentsum() {
        return commentsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_ticket.commentsum
     *
     * @param commentsum the value for shop_ticket.commentsum
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCommentsum(Integer commentsum) {
        this.commentsum = commentsum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_ticket.overtime
     *
     * @return the value of shop_ticket.overtime
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Date getOvertime() {
        return overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_ticket.overtime
     *
     * @param overtime the value for shop_ticket.overtime
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setOvertime(Date overtime) {
        this.overtime = overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_ticket.ticketname
     *
     * @return the value of shop_ticket.ticketname
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getTicketname() {
        return ticketname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_ticket.ticketname
     *
     * @param ticketname the value for shop_ticket.ticketname
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setTicketname(String ticketname) {
        this.ticketname = ticketname == null ? null : ticketname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_ticket.ticketimg
     *
     * @return the value of shop_ticket.ticketimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getTicketimg() {
        return ticketimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_ticket.ticketimg
     *
     * @param ticketimg the value for shop_ticket.ticketimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setTicketimg(String ticketimg) {
        this.ticketimg = ticketimg == null ? null : ticketimg.trim();
    }
}