package com.shiyu.demo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserIndent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_indent.indentid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer indentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_indent.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_indent.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_indent.indenttype
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer indenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_indent.createdate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_indent.pricesum
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private BigDecimal pricesum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_indent.mealtime
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Date mealtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_indent.menuid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer menuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_indent.indentid
     *
     * @return the value of user_indent.indentid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getIndentid() {
        return indentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_indent.indentid
     *
     * @param indentid the value for user_indent.indentid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setIndentid(Integer indentid) {
        this.indentid = indentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_indent.userid
     *
     * @return the value of user_indent.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_indent.userid
     *
     * @param userid the value for user_indent.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_indent.shopid
     *
     * @return the value of user_indent.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_indent.shopid
     *
     * @param shopid the value for user_indent.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_indent.indenttype
     *
     * @return the value of user_indent.indenttype
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getIndenttype() {
        return indenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_indent.indenttype
     *
     * @param indenttype the value for user_indent.indenttype
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setIndenttype(Integer indenttype) {
        this.indenttype = indenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_indent.createdate
     *
     * @return the value of user_indent.createdate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_indent.createdate
     *
     * @param createdate the value for user_indent.createdate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_indent.pricesum
     *
     * @return the value of user_indent.pricesum
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public BigDecimal getPricesum() {
        return pricesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_indent.pricesum
     *
     * @param pricesum the value for user_indent.pricesum
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setPricesum(BigDecimal pricesum) {
        this.pricesum = pricesum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_indent.mealtime
     *
     * @return the value of user_indent.mealtime
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Date getMealtime() {
        return mealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_indent.mealtime
     *
     * @param mealtime the value for user_indent.mealtime
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setMealtime(Date mealtime) {
        this.mealtime = mealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_indent.menuid
     *
     * @return the value of user_indent.menuid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_indent.menuid
     *
     * @param menuid the value for user_indent.menuid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }
}