package com.shiyu.demo.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserIndentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public UserIndentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIndentidIsNull() {
            addCriterion("indentid is null");
            return (Criteria) this;
        }

        public Criteria andIndentidIsNotNull() {
            addCriterion("indentid is not null");
            return (Criteria) this;
        }

        public Criteria andIndentidEqualTo(Integer value) {
            addCriterion("indentid =", value, "indentid");
            return (Criteria) this;
        }

        public Criteria andIndentidNotEqualTo(Integer value) {
            addCriterion("indentid <>", value, "indentid");
            return (Criteria) this;
        }

        public Criteria andIndentidGreaterThan(Integer value) {
            addCriterion("indentid >", value, "indentid");
            return (Criteria) this;
        }

        public Criteria andIndentidGreaterThanOrEqualTo(Integer value) {
            addCriterion("indentid >=", value, "indentid");
            return (Criteria) this;
        }

        public Criteria andIndentidLessThan(Integer value) {
            addCriterion("indentid <", value, "indentid");
            return (Criteria) this;
        }

        public Criteria andIndentidLessThanOrEqualTo(Integer value) {
            addCriterion("indentid <=", value, "indentid");
            return (Criteria) this;
        }

        public Criteria andIndentidIn(List<Integer> values) {
            addCriterion("indentid in", values, "indentid");
            return (Criteria) this;
        }

        public Criteria andIndentidNotIn(List<Integer> values) {
            addCriterion("indentid not in", values, "indentid");
            return (Criteria) this;
        }

        public Criteria andIndentidBetween(Integer value1, Integer value2) {
            addCriterion("indentid between", value1, value2, "indentid");
            return (Criteria) this;
        }

        public Criteria andIndentidNotBetween(Integer value1, Integer value2) {
            addCriterion("indentid not between", value1, value2, "indentid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andShopidIsNull() {
            addCriterion("shopid is null");
            return (Criteria) this;
        }

        public Criteria andShopidIsNotNull() {
            addCriterion("shopid is not null");
            return (Criteria) this;
        }

        public Criteria andShopidEqualTo(Integer value) {
            addCriterion("shopid =", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotEqualTo(Integer value) {
            addCriterion("shopid <>", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThan(Integer value) {
            addCriterion("shopid >", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidGreaterThanOrEqualTo(Integer value) {
            addCriterion("shopid >=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThan(Integer value) {
            addCriterion("shopid <", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidLessThanOrEqualTo(Integer value) {
            addCriterion("shopid <=", value, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidIn(List<Integer> values) {
            addCriterion("shopid in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotIn(List<Integer> values) {
            addCriterion("shopid not in", values, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidBetween(Integer value1, Integer value2) {
            addCriterion("shopid between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andShopidNotBetween(Integer value1, Integer value2) {
            addCriterion("shopid not between", value1, value2, "shopid");
            return (Criteria) this;
        }

        public Criteria andIndenttypeIsNull() {
            addCriterion("indenttype is null");
            return (Criteria) this;
        }

        public Criteria andIndenttypeIsNotNull() {
            addCriterion("indenttype is not null");
            return (Criteria) this;
        }

        public Criteria andIndenttypeEqualTo(Integer value) {
            addCriterion("indenttype =", value, "indenttype");
            return (Criteria) this;
        }

        public Criteria andIndenttypeNotEqualTo(Integer value) {
            addCriterion("indenttype <>", value, "indenttype");
            return (Criteria) this;
        }

        public Criteria andIndenttypeGreaterThan(Integer value) {
            addCriterion("indenttype >", value, "indenttype");
            return (Criteria) this;
        }

        public Criteria andIndenttypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("indenttype >=", value, "indenttype");
            return (Criteria) this;
        }

        public Criteria andIndenttypeLessThan(Integer value) {
            addCriterion("indenttype <", value, "indenttype");
            return (Criteria) this;
        }

        public Criteria andIndenttypeLessThanOrEqualTo(Integer value) {
            addCriterion("indenttype <=", value, "indenttype");
            return (Criteria) this;
        }

        public Criteria andIndenttypeIn(List<Integer> values) {
            addCriterion("indenttype in", values, "indenttype");
            return (Criteria) this;
        }

        public Criteria andIndenttypeNotIn(List<Integer> values) {
            addCriterion("indenttype not in", values, "indenttype");
            return (Criteria) this;
        }

        public Criteria andIndenttypeBetween(Integer value1, Integer value2) {
            addCriterion("indenttype between", value1, value2, "indenttype");
            return (Criteria) this;
        }

        public Criteria andIndenttypeNotBetween(Integer value1, Integer value2) {
            addCriterion("indenttype not between", value1, value2, "indenttype");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createdate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createdate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createdate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createdate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createdate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createdate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createdate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createdate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createdate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createdate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createdate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createdate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andPricesumIsNull() {
            addCriterion("pricesum is null");
            return (Criteria) this;
        }

        public Criteria andPricesumIsNotNull() {
            addCriterion("pricesum is not null");
            return (Criteria) this;
        }

        public Criteria andPricesumEqualTo(BigDecimal value) {
            addCriterion("pricesum =", value, "pricesum");
            return (Criteria) this;
        }

        public Criteria andPricesumNotEqualTo(BigDecimal value) {
            addCriterion("pricesum <>", value, "pricesum");
            return (Criteria) this;
        }

        public Criteria andPricesumGreaterThan(BigDecimal value) {
            addCriterion("pricesum >", value, "pricesum");
            return (Criteria) this;
        }

        public Criteria andPricesumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pricesum >=", value, "pricesum");
            return (Criteria) this;
        }

        public Criteria andPricesumLessThan(BigDecimal value) {
            addCriterion("pricesum <", value, "pricesum");
            return (Criteria) this;
        }

        public Criteria andPricesumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pricesum <=", value, "pricesum");
            return (Criteria) this;
        }

        public Criteria andPricesumIn(List<BigDecimal> values) {
            addCriterion("pricesum in", values, "pricesum");
            return (Criteria) this;
        }

        public Criteria andPricesumNotIn(List<BigDecimal> values) {
            addCriterion("pricesum not in", values, "pricesum");
            return (Criteria) this;
        }

        public Criteria andPricesumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pricesum between", value1, value2, "pricesum");
            return (Criteria) this;
        }

        public Criteria andPricesumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pricesum not between", value1, value2, "pricesum");
            return (Criteria) this;
        }

        public Criteria andMealtimeIsNull() {
            addCriterion("mealtime is null");
            return (Criteria) this;
        }

        public Criteria andMealtimeIsNotNull() {
            addCriterion("mealtime is not null");
            return (Criteria) this;
        }

        public Criteria andMealtimeEqualTo(Date value) {
            addCriterion("mealtime =", value, "mealtime");
            return (Criteria) this;
        }

        public Criteria andMealtimeNotEqualTo(Date value) {
            addCriterion("mealtime <>", value, "mealtime");
            return (Criteria) this;
        }

        public Criteria andMealtimeGreaterThan(Date value) {
            addCriterion("mealtime >", value, "mealtime");
            return (Criteria) this;
        }

        public Criteria andMealtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mealtime >=", value, "mealtime");
            return (Criteria) this;
        }

        public Criteria andMealtimeLessThan(Date value) {
            addCriterion("mealtime <", value, "mealtime");
            return (Criteria) this;
        }

        public Criteria andMealtimeLessThanOrEqualTo(Date value) {
            addCriterion("mealtime <=", value, "mealtime");
            return (Criteria) this;
        }

        public Criteria andMealtimeIn(List<Date> values) {
            addCriterion("mealtime in", values, "mealtime");
            return (Criteria) this;
        }

        public Criteria andMealtimeNotIn(List<Date> values) {
            addCriterion("mealtime not in", values, "mealtime");
            return (Criteria) this;
        }

        public Criteria andMealtimeBetween(Date value1, Date value2) {
            addCriterion("mealtime between", value1, value2, "mealtime");
            return (Criteria) this;
        }

        public Criteria andMealtimeNotBetween(Date value1, Date value2) {
            addCriterion("mealtime not between", value1, value2, "mealtime");
            return (Criteria) this;
        }

        public Criteria andMenuidIsNull() {
            addCriterion("menuid is null");
            return (Criteria) this;
        }

        public Criteria andMenuidIsNotNull() {
            addCriterion("menuid is not null");
            return (Criteria) this;
        }

        public Criteria andMenuidEqualTo(Integer value) {
            addCriterion("menuid =", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotEqualTo(Integer value) {
            addCriterion("menuid <>", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidGreaterThan(Integer value) {
            addCriterion("menuid >", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidGreaterThanOrEqualTo(Integer value) {
            addCriterion("menuid >=", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidLessThan(Integer value) {
            addCriterion("menuid <", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidLessThanOrEqualTo(Integer value) {
            addCriterion("menuid <=", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidIn(List<Integer> values) {
            addCriterion("menuid in", values, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotIn(List<Integer> values) {
            addCriterion("menuid not in", values, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidBetween(Integer value1, Integer value2) {
            addCriterion("menuid between", value1, value2, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotBetween(Integer value1, Integer value2) {
            addCriterion("menuid not between", value1, value2, "menuid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_indent
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 26 19:29:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_indent
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}