package com.shiyu.demo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.score
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.flavor
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer flavor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.service
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer service;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.enviorment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer enviorment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.evaluate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String evaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.commentimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String commentimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.averageprice
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private BigDecimal averageprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.menuid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.car
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String car;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.createdate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.commenttop
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer commenttop;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.id
     *
     * @return the value of user_comment.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.id
     *
     * @param id the value for user_comment.id
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.userid
     *
     * @return the value of user_comment.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.userid
     *
     * @param userid the value for user_comment.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.shopid
     *
     * @return the value of user_comment.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.shopid
     *
     * @param shopid the value for user_comment.shopid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.score
     *
     * @return the value of user_comment.score
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.score
     *
     * @param score the value for user_comment.score
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.flavor
     *
     * @return the value of user_comment.flavor
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getFlavor() {
        return flavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.flavor
     *
     * @param flavor the value for user_comment.flavor
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setFlavor(Integer flavor) {
        this.flavor = flavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.service
     *
     * @return the value of user_comment.service
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.service
     *
     * @param service the value for user_comment.service
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setService(Integer service) {
        this.service = service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.enviorment
     *
     * @return the value of user_comment.enviorment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getEnviorment() {
        return enviorment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.enviorment
     *
     * @param enviorment the value for user_comment.enviorment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setEnviorment(Integer enviorment) {
        this.enviorment = enviorment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.evaluate
     *
     * @return the value of user_comment.evaluate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getEvaluate() {
        return evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.evaluate
     *
     * @param evaluate the value for user_comment.evaluate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setEvaluate(String evaluate) {
        this.evaluate = evaluate == null ? null : evaluate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.commentimg
     *
     * @return the value of user_comment.commentimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getCommentimg() {
        return commentimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.commentimg
     *
     * @param commentimg the value for user_comment.commentimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCommentimg(String commentimg) {
        this.commentimg = commentimg == null ? null : commentimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.averageprice
     *
     * @return the value of user_comment.averageprice
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public BigDecimal getAverageprice() {
        return averageprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.averageprice
     *
     * @param averageprice the value for user_comment.averageprice
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setAverageprice(BigDecimal averageprice) {
        this.averageprice = averageprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.menuid
     *
     * @return the value of user_comment.menuid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.menuid
     *
     * @param menuid the value for user_comment.menuid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.car
     *
     * @return the value of user_comment.car
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getCar() {
        return car;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.car
     *
     * @param car the value for user_comment.car
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCar(String car) {
        this.car = car == null ? null : car.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.createdate
     *
     * @return the value of user_comment.createdate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.createdate
     *
     * @param createdate the value for user_comment.createdate
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.commenttop
     *
     * @return the value of user_comment.commenttop
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getCommenttop() {
        return commenttop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.commenttop
     *
     * @param commenttop the value for user_comment.commenttop
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCommenttop(Integer commenttop) {
        this.commenttop = commenttop;
    }
}