package com.shiyu.demo.entity;

import java.util.Date;

public class UserLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.username
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.userphone
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String userphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.userpwd
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String userpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.usersex
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Integer usersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.userads
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String userads;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.usertext
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String usertext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.userimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String userimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.created_time
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.userid
     *
     * @return the value of user_log.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.userid
     *
     * @param userid the value for user_log.userid
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.username
     *
     * @return the value of user_log.username
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.username
     *
     * @param username the value for user_log.username
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.userphone
     *
     * @return the value of user_log.userphone
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.userphone
     *
     * @param userphone the value for user_log.userphone
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone == null ? null : userphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.userpwd
     *
     * @return the value of user_log.userpwd
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.userpwd
     *
     * @param userpwd the value for user_log.userpwd
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd == null ? null : userpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.usersex
     *
     * @return the value of user_log.usersex
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Integer getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.usersex
     *
     * @param usersex the value for user_log.usersex
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUsersex(Integer usersex) {
        this.usersex = usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.userads
     *
     * @return the value of user_log.userads
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getUserads() {
        return userads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.userads
     *
     * @param userads the value for user_log.userads
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUserads(String userads) {
        this.userads = userads == null ? null : userads.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.usertext
     *
     * @return the value of user_log.usertext
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getUsertext() {
        return usertext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.usertext
     *
     * @param usertext the value for user_log.usertext
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUsertext(String usertext) {
        this.usertext = usertext == null ? null : usertext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.userimg
     *
     * @return the value of user_log.userimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getUserimg() {
        return userimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.userimg
     *
     * @param userimg the value for user_log.userimg
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setUserimg(String userimg) {
        this.userimg = userimg == null ? null : userimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.code
     *
     * @return the value of user_log.code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.code
     *
     * @param code the value for user_log.code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.created_time
     *
     * @return the value of user_log.created_time
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.created_time
     *
     * @param createdTime the value for user_log.created_time
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}