package com.shiyu.demo.mapper;

import com.shiyu.demo.entity.AuthCode;
import com.shiyu.demo.entity.AuthCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int countByExample(AuthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByExample(AuthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insert(AuthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insertSelective(AuthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    List<AuthCode> selectByExample(AuthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    AuthCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") AuthCode record, @Param("example") AuthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExample(@Param("record") AuthCode record, @Param("example") AuthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKeySelective(AuthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_code
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKey(AuthCode record);

    void deleteCode(String userphone);//根据手机号删除验证码

    AuthCode getCodeByMobile(String userphone);//根据手机号查询验证码

    void addCode(AuthCode authCode);
}