package com.shiyu.demo.mapper;

import com.shiyu.demo.entity.CommunityPost;
import com.shiyu.demo.entity.CommunityPostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommunityPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int countByExample(CommunityPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByExample(CommunityPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insert(CommunityPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insertSelective(CommunityPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    List<CommunityPost> selectByExample(CommunityPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    CommunityPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") CommunityPost record, @Param("example") CommunityPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExample(@Param("record") CommunityPost record, @Param("example") CommunityPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKeySelective(CommunityPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_post
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKey(CommunityPost record);
}