package com.shiyu.demo.mapper;

import com.shiyu.demo.entity.CommunityImg;
import com.shiyu.demo.entity.CommunityImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommunityImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int countByExample(CommunityImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByExample(CommunityImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insert(CommunityImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insertSelective(CommunityImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    List<CommunityImg> selectByExample(CommunityImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    CommunityImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") CommunityImg record, @Param("example") CommunityImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExample(@Param("record") CommunityImg record, @Param("example") CommunityImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKeySelective(CommunityImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKey(CommunityImg record);
}