package com.shiyu.demo.mapper;

import com.shiyu.demo.entity.PostImg;
import com.shiyu.demo.entity.PostImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int countByExample(PostImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByExample(PostImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insert(PostImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insertSelective(PostImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    List<PostImg> selectByExample(PostImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    PostImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") PostImg record, @Param("example") PostImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExample(@Param("record") PostImg record, @Param("example") PostImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKeySelective(PostImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_img
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKey(PostImg record);
}