package com.shiyu.demo.mapper;

import com.shiyu.demo.entity.PostComment;
import com.shiyu.demo.entity.PostCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int countByExample(PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByExample(PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insert(PostComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insertSelective(PostComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    List<PostComment> selectByExample(PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    PostComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") PostComment record, @Param("example") PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExample(@Param("record") PostComment record, @Param("example") PostCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKeySelective(PostComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKey(PostComment record);
}