package com.shiyu.demo.mapper;

import com.shiyu.demo.entity.RoleRoot;
import com.shiyu.demo.entity.RoleRootExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleRootMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_root
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int countByExample(RoleRootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_root
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByExample(RoleRootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_root
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_root
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insert(RoleRoot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_root
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insertSelective(RoleRoot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_root
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    List<RoleRoot> selectByExample(RoleRootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_root
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    RoleRoot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_root
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") RoleRoot record, @Param("example") RoleRootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_root
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExample(@Param("record") RoleRoot record, @Param("example") RoleRootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_root
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKeySelective(RoleRoot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_root
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKey(RoleRoot record);
}