package com.shiyu.demo.mapper;

import com.shiyu.demo.entity.ShopInfo;
import com.shiyu.demo.entity.ShopInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int countByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByPrimaryKey(Integer shopid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insert(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insertSelective(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    List<ShopInfo> selectByExample(ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    ShopInfo selectByPrimaryKey(Integer shopid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ShopInfo record, @Param("example") ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExample(@Param("record") ShopInfo record, @Param("example") ShopInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKeySelective(ShopInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_info
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKey(ShopInfo record);
}