package com.shiyu.demo.mapper;

import com.shiyu.demo.entity.ShopLog;
import com.shiyu.demo.entity.ShopLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int countByExample(ShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByExample(ShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByPrimaryKey(Integer shopid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insert(ShopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insertSelective(ShopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    List<ShopLog> selectByExample(ShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    ShopLog selectByPrimaryKey(Integer shopid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ShopLog record, @Param("example") ShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExample(@Param("record") ShopLog record, @Param("example") ShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKeySelective(ShopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKey(ShopLog record);

    int getShopCountByMobile(String shopphone);

    void addShop(ShopLog shopLog);

    int updateShopname(ShopLog shopLog);

    Integer getShopId(String shopphone);

    Integer getShop(String shopphone);
}