package com.shiyu.demo.mapper;

import com.shiyu.demo.entity.ShopPhoto;
import com.shiyu.demo.entity.ShopPhotoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_photo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int countByExample(ShopPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_photo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByExample(ShopPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_photo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_photo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insert(ShopPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_photo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insertSelective(ShopPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_photo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    List<ShopPhoto> selectByExample(ShopPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_photo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    ShopPhoto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_photo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ShopPhoto record, @Param("example") ShopPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_photo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExample(@Param("record") ShopPhoto record, @Param("example") ShopPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_photo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKeySelective(ShopPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_photo
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKey(ShopPhoto record);
}