package com.shiyu.demo.mapper;

import com.shiyu.demo.entity.ShopEnvironment;
import com.shiyu.demo.entity.ShopEnvironmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopEnvironmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int countByExample(ShopEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByExample(ShopEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insert(ShopEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insertSelective(ShopEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    List<ShopEnvironment> selectByExample(ShopEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    ShopEnvironment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ShopEnvironment record, @Param("example") ShopEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExample(@Param("record") ShopEnvironment record, @Param("example") ShopEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKeySelective(ShopEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_environment
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKey(ShopEnvironment record);
}