package com.shiyu.demo.mapper;

import com.shiyu.demo.entity.UserSave;
import com.shiyu.demo.entity.UserSaveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_save
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int countByExample(UserSaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_save
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByExample(UserSaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_save
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_save
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insert(UserSave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_save
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int insertSelective(UserSave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_save
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    List<UserSave> selectByExample(UserSaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_save
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    UserSave selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_save
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserSave record, @Param("example") UserSaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_save
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByExample(@Param("record") UserSave record, @Param("example") UserSaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_save
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKeySelective(UserSave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_save
     *
     * @mbggenerated Fri Apr 26 19:29:00 CST 2019
     */
    int updateByPrimaryKey(UserSave record);
}